package com.school.controller;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.school.dao.AdminDao;
import com.school.model.AdminBasicInfo;
import com.school.model.AdminUser;
import com.school.model.SignUpAttemptDTO;
import com.school.service.AdminService;
import com.school.signup.EmailSending;
import com.school.signup.EmailSendingHelper;




@Controller
public class AdminRegistration {
	
	@Autowired
	private AdminDao loginDao;
	@Autowired
	private EmailSending emailSending;
	@Autowired
	private EmailSendingHelper emailSendingHelper;
	
	@Autowired
	private AdminService loginService;
	
	private SignUpAttemptDTO signUpAttemptDTO;
	private String activationCode;
	private AdminBasicInfo userInfo;
	public final String UPLOAD_DIRECTORY = "E:/Picture";

	
	@RequestMapping(value = "/adminindex", method = RequestMethod.GET)
	  public ModelAndView showRegister(@ModelAttribute("adminReg") ModelAndView model) throws IOException {
		// ModelAndView mav = new ModelAndView();
	    model.addObject("adminReg", new AdminBasicInfo());
	    model.setViewName("adminRegistration");
	    return model;
	  }

	
	  @RequestMapping(value = "/AdminRegProcess", method = RequestMethod.POST)
	  public ModelAndView signUp(@ModelAttribute("adminReg") AdminBasicInfo userBasicInfo) {
		  setActivationCode("");
		  userInfo=new AdminBasicInfo();
		  long generatedCodeHelper1=999999;
		  long autogeneratedCodeHelper2 = generatedCodeHelper1 + new Date().getTime();		
		  long finalAutogeneratedCode = autogeneratedCodeHelper2 % 10000;
		  ModelAndView mnv=null;
		  
		  AdminBasicInfo user=loginDao.validInfo(userBasicInfo);
		  if(user==null){
			  
			  String photoName = userBasicInfo.getFiles().getOriginalFilename();
				Path path = Paths.get(UPLOAD_DIRECTORY + File.separator + photoName);
				try {
					Files.write(path, userBasicInfo.getFiles().getBytes());
					userBasicInfo.setPhotoPath(photoName);
				} catch (Exception e) {
					e.printStackTrace();
				}
			  loginDao.deleteExtraObject(userBasicInfo.getEmail());
			  signUpAttemptDTO =new SignUpAttemptDTO();
			  signUpAttemptDTO.setEmail(userBasicInfo.getEmail());
			  signUpAttemptDTO.setDate(new Date());
			  signUpAttemptDTO.setStatus(1);
			  signUpAttemptDTO.setActivationCode(String.valueOf(finalAutogeneratedCode));
			  
			  
			  loginDao.createSignUpAttempt(signUpAttemptDTO);
			  userInfo.setUsername(userBasicInfo.getUsername());
			  userInfo.setPassword(userBasicInfo.getPassword());
			  userInfo.setFirstname(userBasicInfo.getFirstname());
			  userInfo.setLastname(userBasicInfo.getLastname());
			  userInfo.setEmail(userBasicInfo.getEmail());
			  userInfo.setAddress(userBasicInfo.getAddress());
			  userInfo.setPhone(userBasicInfo.getPhone());
			  userInfo.setPhotoPath(userBasicInfo.getPhotoPath());
			
			  emailSending.setReceipient(userBasicInfo.getEmail());
			  emailSending.setSubject(" Activation Code");
			  emailSending.setContent("Your Accout Activation Code for is: " + finalAutogeneratedCode); 
			  emailSendingHelper.setEmailSending(emailSending); 
			  emailSendingHelper.sendMail();
			  
			  mnv = new ModelAndView();
			  mnv.addObject("active", new SignUpAttemptDTO());
			  mnv.setViewName("activation");
		  }else {
			
			mnv = new ModelAndView("adminRegistration");
			mnv.addObject("message", "Sorry you have all ready an account...!!");
		}
		  
		  
		  return mnv;
	  }
	  
	  
	  	@RequestMapping(value= "/activation", method = RequestMethod.POST)
		public ModelAndView saveActivation(@ModelAttribute("active") SignUpAttemptDTO sign) {
		  
	  	 ModelAndView mav = null;
	  	 
	  	 
		 SignUpAttemptDTO activation=loginDao.findActivationCode(sign);
		 
		 if (activation!=null) { 
			AdminUser loginUser=new AdminUser();
			AdminBasicInfo userBasicInfo=new AdminBasicInfo();
			userBasicInfo.setUsername(userInfo.getUsername());
			userBasicInfo.setPassword(userInfo.getPassword());
			userBasicInfo.setFirstname(userInfo.getFirstname());
			userBasicInfo.setLastname(userInfo.getLastname());
			userBasicInfo.setEmail(userInfo.getEmail());
			userBasicInfo.setPhone(userInfo.getPhone());
			userBasicInfo.setAddress(userInfo.getAddress());
			userBasicInfo.setPhotoPath(userInfo.getPhotoPath());
			
			loginUser.setEmail(userInfo.getEmail());
			loginUser.setPassword(userInfo.getPassword());
			
			loginService.registerUserInfo(userBasicInfo);
			loginService.saveLogin(loginUser);
			
			mav = new ModelAndView();
		    mav.addObject("admin", new AdminUser());
		    mav.setViewName("AdminLogin");
		} else {
			System.out.println("all ready exiting in database");
			mav = new ModelAndView("activation");
		    mav.addObject("message", "Sorry your activation code was wrong...!!");
		}
		
		    return mav;
		}
		

	public String getActivationCode() {
		return activationCode;
	}

	public void setActivationCode(String activationCode) {
		this.activationCode = activationCode;
	}

}
